from __future__ import annotations

from ..config.commands import cmd_configure, cmd_default, cmd_init, cmd_validate
from .handlers import (
    cmd_backup,
    cmd_battleye,
    cmd_check,
    cmd_completion,
    cmd_deploy,
    cmd_doctor,
    cmd_firewall,
    cmd_fix,
    cmd_export,
    cmd_info,
    cmd_hub,
    cmd_import,
    cmd_invite,
    cmd_install,
    cmd_linux_user,
    cmd_linuxgsm,
    cmd_menu,
    cmd_mods,
    cmd_ports,
    cmd_query,
    cmd_render,
    cmd_resources,
    cmd_service,
    cmd_setup,
    cmd_status,
    cmd_systemd,
    cmd_update,
    cmd_web,
    cmd_windows_task,
    cmd_workshop,
)
from .lifecycle import cmd_debug, cmd_logs, cmd_pause, cmd_restart, cmd_resume, cmd_start, cmd_stop


def dispatch_table() -> dict[str, callable]:
    return {
        "init": cmd_init,
        "configure": cmd_configure,
        "default": cmd_default,
        "validate": cmd_validate,
        "setup": cmd_setup,
        "check": cmd_check,
        "completion": cmd_completion,
        "export": cmd_export,
        "import": cmd_import,
        "fix": cmd_fix,
        "render": cmd_render,
        "install": cmd_install,
        "update": cmd_update,
        "start": cmd_start,
        "up": cmd_start,
        "stop": cmd_stop,
        "down": cmd_stop,
        "restart": cmd_restart,
        "reload": cmd_restart,
        "pause": cmd_pause,
        "resume": cmd_resume,
        "debug": cmd_debug,
        "status": cmd_status,
        "info": cmd_info,
        "hub": cmd_hub,
        "invite": cmd_invite,
        "resources": cmd_resources,
        "query": cmd_query,
        "logs": cmd_logs,
        "tail": cmd_logs,
        "ports": cmd_ports,
        "service": cmd_service,
        "firewall": cmd_firewall,
        "backup": cmd_backup,
        "mods": cmd_mods,
        "systemd": cmd_systemd,
        "windows-task": cmd_windows_task,
        "battleye": cmd_battleye,
        "linuxgsm": cmd_linuxgsm,
        "doctor": cmd_doctor,
        "linux-user": cmd_linux_user,
        "deploy": cmd_deploy,
        "launch": cmd_deploy,
        "web": cmd_web,
        "open": cmd_web,
        "workshop": cmd_workshop,
        "menu": cmd_menu,
    }
