STABLE_APP_ID = "1874900"
EXPERIMENTAL_APP_ID = "1890870"
DEFAULT_CONFIG = "deployer.json"

SUPPORTED_CLIENTS_CROSSPLAY = ["PLATFORM_PC", "PLATFORM_XBL", "PLATFORM_PSN"]
SUPPORTED_CLIENTS_PC_ONLY = ["PLATFORM_PC"]

